# Generated by Django 4.1.7 on 2023-03-24 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_auteur_idea_author_rename_detail_idea_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='likes',
        ),
    ]
