# Generated by Django 4.1.7 on 2023-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_idea_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
