# Generated by Django 4.1.7 on 2023-03-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_idea_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
